= Declarations

++++
<link rel="stylesheet" href="../style.css" type="text/css">
++++

:tab: &nbsp;&nbsp;&nbsp;&nbsp;
:hardbreaks-option:

:star: *
:under: _

`_type-specifier_`: one of
{tab} `*wild*` `*bool*` `*byte*`  `*char*`
{tab} `*int16*` `*int*` `*int32*` `*int64*`
{tab} `*nat16*` `*nat*` `*nat32*` `*nat64*`
{tab} `*real32*` `*real*` `*real64*`
{tab} `*cplex32*` `*cplex*` `*cplex64*`

`_type-qualifier_`: one of
{tab} `*const*` `*unique*` `*volatile*` `*atomic*`

`_type-qualifier-list_`:
{tab} `_type-qualifier_`
{tab} `_type-qualifier-list_` `_type-qualifier_`

`_align-specifier_`:
{tab} `*align*` `*(*` `_type-name_` `*)*`
{tab} `*align*` `*(*` `_expression_` `*)*`

`_specifier-qualifier-list_`:
{tab} `_type-qualifier-list_`~opt~ `_align-specifier_`~opt~ `_type-specifier_`

`_direct-abstract-declarator_`:
{tab} `*(*` `_abstract-declarator_` `*)*`
{tab} `_direct-abstract-declarator_` `*[*` `_type-qualifier-list_`~opt~ `_single-expression_`~opt~ `*]*`
{tab} `_direct-abstract-declarator_` `*[*` `_type-qualifier-list_`~opt~  `*\<=*` `_single-expression_` `*]*`
{tab} `_direct-abstract-declarator_` `*[*` `_type-qualifier-list_`~opt~ `*{star}*` `*]*`

`_pointer_`:
{tab} `*^*` `_type-qualifier-list_`~opt~
{tab} `*^*` `_type-qualifier-list_`~opt~ `_pointer_`

`_abstract-declarator_`:
{tab} `_pointer_`
{tab} `_pointer_`~opt~ `_direct-abstract-declarator_`

`_type-name_`:
{tab} `_specifier-qualifier-list_` `_abstract-declarator_`~opt~

`_storage-class-specifier_`: one of
{tab} `*register*` `*static*`
{tab} `*type*`

// Continue
