= Expressions

++++
<link rel="stylesheet" href="../style.css" type="text/css">
++++

:tab: &nbsp;&nbsp;&nbsp;&nbsp;
:hardbreaks-option:

:star: *

`_primary-expression_`:
{tab} `_numeric-constant_`
{tab} `_character-constant_`
{tab} `_string-constant_`
{tab} `_identifier_`
{tab} `_file-identifier_`
{tab} `*(*` `_expression_` `*)*`
{tab} `_initializer-list-expression_`
{tab} `_primary-keyword_`
`_file-identifier_`:
{tab} `_identifier_` `*::*` `_identifier_`
`_initializer-list-expression_`:
{tab} `*[*` `*]*`
{tab} `*[*` `_initializer-list_` `*,*`~opt~ `*]*`
`_primary-keyword_`: one of
{tab} `*true*` `*false*` `*null*`

`_postfix-expression_`:
{tab} `_primary-expression_`
{tab} `_postfix-expression_` `*.*` `_identifier_`
{tab} `_postfix-expression_` `*?.*` `_identifier_`
{tab} `_postfix-expression_` `*[*` `_expression_` `*]*`
{tab} `_postfix-call-expression_`

`_postfix-call-expression_`:
{tab} `_postfix-expression_` `*(*`  `_argument-expression-list_`~opt~  `_default-arguments_`~opt~ `*)*`
`_argument-expression-list_`:
{tab} `_single-expression_`
{tab} `_argument-expression-list_` `*,*` `_single-expression_`
`_default-arguments_`:
{tab} `*,*` `_default-argument-list_`
`_default-argument-list_`:
{tab} `_identifier_` `*=*` `_single-expression_`
{tab} `_default-argument-list_` `*,*` `_identifier_` `*=*` `_single-expression_`

`_unary-expression_`:
{tab} `_postfix-expression_`
{tab} `_unary-operator_` `_unary-expression_`
{tab} `_size-expression_`
{tab} `_align-expression_`
`_unary-operator_`: one of
{tab} `*+*` `*-*` `*!*` `*^*` `*@*` `*await*`

`_size-expression_`:
{tab} `*sizeof*` `_unary-expression_`
{tab} `*sizeof*` `*(*` `_type-name_` `*)*`

`_align-expression_`:
{tab} `*alignof*` `_unary-expression_`
{tab} `*alignof*` `*(*` `_type-name_` `*)*`

`_multiplicative-expression_`:
{tab} `_unary-expression_`
{tab} `_multiplicative-expression_` `_multiplicative-operator_` `_unary-expression_`
`_multiplicative-operator_`: one of
{tab} `*{star}*` `*/*` `*%*`

`_additive-expression_`:
{tab} `_multiplicative-expression_`
{tab} `_additive-expression_` `_additive-operator_` `_multiplicative-expression_`
`_additive-operator_`: one of
{tab} `*+*` `*-*`

`_shift-expression_`:
{tab} `_additive-expression_`
{tab} `_shift-expression_` `_shift-operator_` `_additive-expression_`
`_shift-operator_`: one of
{tab} `*<<*` `*>>*`

`_bitwise-and-expression_`:
{tab} `_shift-expression_`
{tab} `_bitwise-and-expression_` `*&*` `_shift-expression_`

`_bitwise-xor-expression_`:
{tab} `_bitwise-and-expression_`
{tab} `_bitwise-xor-expression_` `*$*` `_bitwise-and-expression_`

`_bitwise-or-expression_`:
{tab} `_bitwise-xor-expression_`
{tab} `_bitwise-or-expression_` `*|*` `_bitwise-xor-expression_`

`_allocation-expression_`:
{tab} `_bitwise-or-expression_`
{tab} `*alloc*` `_bitwise-or-expression_` `*null*`~opt~
{tab} `*realloc*` `_allocation-expression_` `*with*` `_bitwise-or-expression_`
{tab} `*unalloc*` `_allocation-expression_`

`_cast-expression_`:
{tab} `_allocation-expression_`
{tab} `_cast-expression_` `*as*` `_type-name_`
{tab} `_cast-expression_` `*as*` `*(*` `_type-name_` `*)*`

`_comparative-expression_`:
{tab} `_cast-expression_`
{tab} `_comparative-expression_` `_comparative-operator_` `_cast-expression_`
`_comparative-operator_`: one of
{tab} `*<*` `*>*` `*\<=*` `*>=*` `*==*` `*!=*`

`_logical-not-expression_`:
{tab} `_comparative-expression_`
{tab} `*not*` `_logical-not-expression_`

`_logical-and-expression_`:
{tab} `_logical-not-expression_`
{tab} `_logical-and-expression_` `*and*` `_logical-not-expression_`

`_logical-xor-expression_`:
{tab} `_logical-and-expression_`
{tab} `_logical-xor-expression_` `*xor*` `_logical-and-expression_`

`_logical-or-expression_`:
{tab} `_logical-xor-expression_`
{tab} `_logical-or-expression_` `*or*` `_logical-and-expression_`

`_conditional-expression_`:
{tab} `_logical-or-expression_`
{tab} `_logical-or-expression_` `*if*` `_expression_` `*else*` `_conditional-expression_`

`_single-expression_`:
{tab} `_conditional-expression_`

`_expression_`:
{tab} `_single-expression_`
{tab} `_expression_` `*,*` `_single-expression_`
